HSAServer/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'HSAServer.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),
    url(r'^main/', include('main.urls', namespace='main')),
    url(r'^admin/', include(admin.site.urls)),
)

main/urls.py
__author__ = 'Hossein Noroozpour'
from django.conf.urls import patterns, url
from main import views


urlpatterns = patterns(
    '',
    url(r'^$', views.index, name='index'),
    url(r'^register/$', views.register, name='register'),
    url(r'^show/$', views.show, name='show'),
    url(r'^(?P<agent_id>\d+)/detail/$', views.detail, name='detail'),
    )

main/models.py
from django.db import models
import datetime
from django.utils import timezone
# Create your models here.


class Agent(models.Model):
    first_name = models.CharField(max_length=255)
    last_name = models.CharField(max_length=255)
    email_address = models.EmailField(max_length=255, unique=True)
    birth_date = models.DateField()
    phone_number = models.CharField(max_length=16)
    home_address = models.CharField(max_length=511)
    work_address = models.CharField(max_length=511)
    key_iv_aes = models.CharField(max_length=128)
    session_key_iv_aes = models.CharField(max_length=128)
    logged_in = models.BooleanField(default=False)
    login_tries = models.PositiveSmallIntegerField()
    last_login_try = models.DateTimeField()
    confirmed = models.BooleanField(default=False)
    registration_date = models.DateTimeField()

    def __str__(self):
        return self.first_name + " " + self.last_name

    def is_registered_recently(self):
        return self.registration_date >= timezone.now() - datetime.timedelta(days=1)


# class Choice(models.Model):
#     question = models.ForeignKey(Question)
#     choice_text = models.CharField(max_length=200)
#     votes = models.IntegerField(default=0)

main/views.py
from django.shortcuts import render
from main.models import Agent
from django.core.handlers.wsgi import WSGIRequest
from django.core.validators import validate_email
from django.core.exceptions import ValidationError
from datetime import datetime
from django.utils.crypto import get_random_string
from django.utils import timezone
from django.db import IntegrityError
from django.core.exceptions import ObjectDoesNotExist

def index(request):
    pass


def register(request):
    """
    :type request: WSGIRequest
    """
    try:
        first_name = request.POST['first-name']
        last_name = request.POST['last-name']
        email_address = request.POST['email-address']
        birth_date = request.POST['birth-date']
        phone_number = request.POST['phone-number']
        home_address = request.POST['home-address']
        work_address = request.POST['work-address']
    except KeyError:
        return render(request, 'main/register.html')
    else:
        try:
            validate_email(email_address)
        except ValidationError:
            return render(request, 'main/register.html', {'error_message': "Please enter a valid email address."})
        try:
            birth_date = datetime.strptime(birth_date, "%Y-%m-%d")
        except ValueError:
            return render(request, 'main/register.html', {'error_message': "Please enter a valid birth date, "
                                                                           + "its format must be: YYYY-MM-DD"})
        try:
            Agent.objects.get(email_address=email_address)
        except ObjectDoesNotExist:
            agent = Agent(first_name=first_name,
                          last_name=last_name,
                          email_address=email_address,
                          birth_date=birth_date,
                          phone_number=phone_number,
                          home_address=home_address,
                          work_address=work_address,
                          key_iv_aes=get_random_string(length=128),
                          session_key_iv_aes=get_random_string(length=128),
                          logged_in=False,
                          login_tries=0,
                          last_login_try=timezone.now(),
                          confirmed=False,
                          registration_date=timezone.now())
            agent.save()
        else:
            return render(request, 'main/register.html', {'error_message': "Your email is registered before."})


def show(request):
    return render(request, 'main/show.html', {'agents_list': Agent.objects.order_by('last_name')})


def detail(request, agent_id):
    pass

main/templates/main/register.html
<!DOCTYPE html>
<html>
<head lang="en">
    <meta charset="UTF-8">
    <title>Registration Form</title>
</head>
<body>
{% if error_message %} <div class="error-message"> {{ error_message }} </div> {% endif %}
<form action="{% url 'main:register' %}" method="post">
{% csrf_token %}
    <div class="input-row">
        <div class="input-label"> Your first name </div>
        <input type="text" name="first-name" id="fist-name" value="Write your first name here."/>
    </div>
    <div class="input-row">
        <div class="input-label"> Your last name </div>
        <input type="text" name="last-name" id="last-name" value="Write your last name here."/>
    </div>
    <div class="input-row">
        <div class="input-label"> Your e-mail address </div>
        <input type="email" name="email-address" id="email-address" value="example@example.exa"/>
    </div>
    <div class="input-row">
        <div class="input-label"> Your birth date </div>
        <input type="date" name="birth-date" id="birth-date"/>
    </div>
    <div class="input-row">
        <div class="input-label"> Your phone number </div>
        <input type="number" name="phone-number" id="phone-number" value="09"/>
    </div>
    <div class="input-row">
        <div class="input-label"> Your home address </div>
        <input type="text" name="home-address" id="home-address"/>
    </div>
    <div class="input-row">
        <div class="input-label"> Your work address </div>
        <input type="text" name="work-address" id="work-address"/>
    </div>
    <input type="submit" value="Submit" />
</form>
</body>
</html>

main/templates/main/show.html
<!DOCTYPE html>
<html>
<head lang="en">
    <meta charset="UTF-8">
    <title>Display Agent Page</title>
</head>
<body>
{% if agents_list %}
    <table>
    {% for agent in agents_list %}
        <tr>
            <th><a href="{% url 'main:detail' agent.id %}">{{ agent.first_name }} {{ agent.last_name }}</a></th>
            <th>{{ agent.email_address }}</th>
            <th>{{ agent.phone_number }}</th>
            <th>{{ agent.home_address }}</th>
            <th>{{ agent.work_address }}</th>
            <th>{{ agent.confirmed }}</th>
            <th>{{ agent.registration_date }}</th>
        </tr>
    {% endfor %}
    </table>
{% else %}
    <p>No Agent is registered now.</p>
{% endif %}
</body>
</html>

main/templates/main/successful-registration.html
<!DOCTYPE html>
<html>
<head lang="en">
    <meta charset="UTF-8">
    <title>Successful registration</title>
</head>
<body>
<p class="alone-info">
    You have registered successfully and after confirmation of the server admin you will receive an email containing your password for connection.
</p>
</body>
</html>